Float interface improvements - and some other things
kalmarek/Arblib.jl pull request #179
Opened 2024-01-17 10:35 UTC by Joel-Dahne

Lately I have been taking a look at interfacing Arblib with [IntervalArithmetic.jl](https://github.com/JuliaIntervals/IntervalArithmetic.jl). In this process I have implemented some functionality that would make this easier. Then I got stuck on a delayed train and ended up fixing less related things in the meantime...

This PR adds the following functionality:
- Adds `typemin` and `typemax` for `Mag`, `Arf` and `Arb`
- Adds `frexp` and `ldexp` for `Arf` and `Arb`. Arb already implements a `frexp` function, so this was easy!
- There is one large commit which improves the conversion to float types and `Complex{T}`, more comments about this below.
- Add support for `T == Float64` in `radius`. This doesn't allocate can be useful for example when heuristically choosing algorithm based on the radius. Since `Float64` has a bounded exponent this will overflow (rounding up) for extremely small or large radius.
- Add support for `T == Arf` in `getball`
- Microoptimization for `Irrational{:φ}`
- Add `log2` and `log10` for `Arb` and `Acb`. These are sometimes used for magnitude estimation in generic Julia code.
- Improve conversion to `Int` and `BigInt`. The conversion to `Int` would previously crash on overflow. One could possibly add conversion to other integer types, but they would just be wrappers around these types anyway. I also added a note about it being nice to support rounding methods such as `round`, `ceil` and `floor`.

Regarding the conversion to floats and complex: 

For `Float64` it now supports specifying the rounding as the second argument when converting. Before it would fall back to a generic Julia implementation if one specified the rounding and I'm not entirely sure that it was completely rigorous. The new version should be faster anyway. Previously we supported giving a `rnd::Arblib.arb_rnd` keyword argument to specify the argument. Since we are now at `1.0` I have opted to keep this implementation as well, though it could be removed at some future point. I also added `Float16` and `Float32` conversion, wrapping the `Float64` one. In particular Makie.jl likes to convert things to `Float32`.

For `BigFloat` it not supports giving the precision and the rounding as arguments in the same format that is mentioned in the docstring of `BigFloat`. Here there is however one design decision that I would like input on. The docstring for `BigFloat` specifies that the default precision is given by `precision(BigFloat)` and the rounding mode by `rounding(BigFloat)`. I have opted to have the precision be given by the precision of the input, and the rounding mode to always be `RoundNearest`. I very much prefer to avoid using the global arguments when possible, they tend to lead to a lot of issues. But contradicting the `BigFloat` documentation could of course also lead to confusion for people. Do you have any thoughts about this?

I have also thought a bit about how to handle conversion of `Arb` to floats. Currently it just converts the midpoint, which is in general what makes the most sense. If one specifies the rounding then this is applied when converting the midpoint. One could imagine the rounding the specify if one wants the midpoint, lower bound or upper bound of the ball. So that one would have something like `Float64(Arb((0, 1))) = 0.5`, `Float64(Arb((0, 1)), RoundDown) = 0.0` and `Float64(Arb((0, 1)), RoundUp) = 1.0`. I think this would have more or less well defined semantics and it could actually be quite convenient in some cases. I believe it would make it play nicely with IntervalArithmetic.jl for example. Do you have any thoughts about this? It would sort of be a breaking change, but only because it earlier used the generic Julia implementation for rounded conversion to `Float64`.

It now supports converstion to `Complex{T}` from `Acb` for any `T`, previously it only supported `Float64`. Well, as long as conversion from `Arb` to `T` is supported. The current implementation has one issue/feature, it allows constructing  a `Complex{ArbRef}` which will then not be freshly allocated by refer to the original `Acb` input. In general we don't allow construction of `Ref` types except if one explicitly asks for a reference. I don't think this is a big deal however, most people would not try to construct a `Complex{ArbRef}`.

Regarding handling of complex values we currently have `complex(::Arb)::Complex{Arb}` and `(im * (x::Arb))::Complex{Arb}`. In my current project I deal with a lot of complex numbers and I have realized that it would probably be better to have both of them convert to `Acb` instead of `Complex{Arb}`. But this would be a highly breaking change, so maybe not something we should do at the moment.

2024-01-18 16:15 UTC, Joel-Dahne commented
@OliverHnt  This could possibly be of some interest to you as well. In particular the conversion with rounding to `Float64` and `BigFloat` I realized we were missing when I tried to interface with IntervalArithmetic.jl. The methods `typemin`, `typemax`, `frexp` and `ldexp` I also added because they were used by IntervalArithmetic.jl.

2024-02-01 20:13 UTC, Joel-Dahne commented
@kalmarek Would you have time to take a look at this? There is no actually hurry from my side, but would be nice to get it merged!

2024-02-05 15:54 UTC, kalmarek commented
@Joel-Dahne I spent the last month traveling and didn't actually open the github page once ;)
I'll look into this tomorrow though, thanks for the patience!

2024-02-05 17:45 UTC, Joel-Dahne commented
No worries, take the time you need! I took the opportunity to push to more changes:
1. Fix `Base.precision` for Julia 1.11-DEV. The internal single argument version of Base._precision was renamed to
Base._precision_with_base_2.
2. Add a non-inplace version of `Arblib.load_string!`, for convenience.

I also thought it would make sense to make a release with the updates, so I have bumped the version to 1.1.

2024-02-05 20:26 UTC, Joel-Dahne commented
I realized that I had made an error in the conversion tests with `Arblib.arb_rnd`, they should hopefully be fixed now! I accidentally added some additional tests for `BigInt` in the same commit, which I'm now too lazy to move to a new commit.

2024-02-06 12:07 UTC, kalmarek requested changes

2024-02-06 13:11 UTC, Joel-Dahne commented on src/conversion.jl
> +Base.Float16(x::MagOrRef, r::arb_rnd) = Float16(Float64(x, r), convert(RoundingMode, r))
That would certainly be clearer! I updated it to be like that.

2024-02-06 13:13 UTC, Joel-Dahne commented on src/conversion.jl
> +end
I have thought about this as well and it would probably make sense. Will keep this in mind for a future PR!

2024-02-07 08:36 UTC, kalmarek approved these changes

2024-02-07 09:28 UTC, merged