Add dedicated [Arb/Acb]Ref[Vector/Matrix] type
kalmarek/Arblib.jl pull request #50
Opened 2020-09-02 06:46 UTC by saschatimme

This tries to resolve the discussion in #44 .

* `[Arb/Acb][Vector/Matrix]` now returns an honest `Arb` (resp. `Acb`)
* `[Arb/Acb]Ref[Vector/Matrix]` is a new type which returns an `ArbRef` (resp. `AcbRef`)
* Possible to convert between these two container formats without allocations 
* Introduces new function `ref(A, i [, j])` to index `[Arb/Acb][Vector/Matrix]` and obtain `ArbRef` (resp. `AcbRef`).

I hope this addresses all concerns @kalmarek  @Joel-Dahne .

2020-09-02 13:06 UTC, kalmarek approved these changes
It's probably too much code for a quick review I did, but let's not wait with this
@Joel-Dahne If you don't have major complaints, let's merge this now and iterate on it later

2020-09-02 17:36 UTC, Joel-Dahne commented
Go ahead and merge!

2020-09-02 19:42 UTC, kalmarek commented
ok, I have one complaint:) `ArbMatrix(::AbstractMatrix, prec=...)` uses default argument and not a `prec` kwarg as it is everywhere else...

2020-09-03 05:45 UTC, saschatimme commented
Oh yes this I also noticed already,  but I didn’t want to sneak this into this PR.  But I can obviously do this :)

2020-09-03 10:49 UTC, kalmarek commented on src/vector.jl
> +    @eval function Base.$jf(v::T, w::T) where {T<:Vectors}
these functions does not even work on the syntactic level ;)
but it's too much work to fix it here, I already did in #56

2020-09-03 10:50 UTC, kalmarek commented on src/matrix.jl
> +    @eval function Base.$jf(A::T, B::T) where {T<:Matrices}
please add one test for each of the functions

2020-09-03 10:52 UTC, kalmarek commented on src/types.jl
> +        $TA(M::$TRefA) = $TA(cstruct(M), precision(M))
please add one tests for each constructors

2020-09-03 10:54 UTC, kalmarek requested changes
we need to make sure the functions run as defined ;)

2020-09-03 16:05 UTC, kalmarek approved these changes

2020-09-03 16:05 UTC, merged

2020-09-03 16:05 UTC, kalmarek commented
yay!